/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat;

import chat.client.ChatClient;
import chat.server.ChatServer;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author Max
 */
public class ChatFrame extends javax.swing.JFrame {

    private static final String SERVER_ADDRESS = "192.168.21.110";
    private static final int SERVER_PORT = 5781;
    private static final int ClientSERVER_PORT = 5782;

    private ChatServer chatServer;
    Date date = new Date();
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy hh:mm");

    File path = new File("Logs");

    /**
     * Creates new form ChatFrame
     */
    public ChatFrame() {
        initComponents();
        jtaChatMessage.requestFocus();
        try {
            chatServer = new ChatServer(ClientSERVER_PORT);
            Thread thread = new Thread(chatServer);

            thread.start();

        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        setLocationRelativeTo(null);

        if (!path.exists()) {
            path.mkdir();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtaChatHistory = new javax.swing.JTextArea();
        jtfIPadress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaChatMessage = new javax.swing.JTextArea();
        jbSendMessage = new javax.swing.JButton();
        jlStatusMessage = new javax.swing.JLabel();
        jbSave = new javax.swing.JButton();
        jlSaveLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtaChatHistory.setEditable(false);
        jtaChatHistory.setColumns(20);
        jtaChatHistory.setRows(14);
        jtaChatHistory.setFocusable(false);
        jScrollPane1.setViewportView(jtaChatHistory);

        jtfIPadress.setText("192.168.21.110");

        jLabel1.setText("IP Address:");

        jtaChatMessage.setColumns(20);
        jtaChatMessage.setRows(5);
        jScrollPane2.setViewportView(jtaChatMessage);

        jbSendMessage.setText("SEND");
        jbSendMessage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jbSendMessageFocusGained(evt);
            }
        });
        jbSendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSendMessageActionPerformed(evt);
            }
        });

        jlStatusMessage.setText(" ");

        jbSave.setText("SAVE");
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });

        jlSaveLabel.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfIPadress, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlStatusMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlSaveLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbSendMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfIPadress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSendMessage)
                    .addComponent(jlStatusMessage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSave)
                    .addComponent(jlSaveLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSendMessageActionPerformed

        String recipient = jtfIPadress.getText();
        String massage = jtaChatMessage.getText();

        if (massage.isEmpty()) {
            jlStatusMessage.setText("enter some message please before");
            return;
        }

        ChatClient chatClient = new ChatClient(SERVER_ADDRESS, SERVER_PORT);
        try {
            chatClient.sendMessage(recipient, massage);
            jtaChatHistory.append(recipient + '\n' + dateFormat.format(date) + '\n' + massage + '\n');
//            jtaChatHistory.append(dateFormat.format(date) + '\n');
//            jtaChatHistory.append(massage + '\n');
            jtaChatMessage.setText(null);
        } catch (IOException ex) {
            jlStatusMessage.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jbSendMessageActionPerformed

    private void jbSendMessageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbSendMessageFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSendMessageFocusGained

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        if (jtaChatHistory.getText().equals("")) {
            jlSaveLabel.setText("Nothing to Save");
        } else {
            File logf = new File(path + File.separator + jtfIPadress.getText() + ".txt");

            try {
                logf.createNewFile();
                FileWriter fl = new FileWriter(logf, true);
                fl.write(jtaChatHistory.getText());
                fl.flush();

            } catch (Exception e) {
                jlSaveLabel.setText("Error " + e);
            }

        }
    }//GEN-LAST:event_jbSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbSave;
    private javax.swing.JButton jbSendMessage;
    private javax.swing.JLabel jlSaveLabel;
    private javax.swing.JLabel jlStatusMessage;
    private javax.swing.JTextArea jtaChatHistory;
    private javax.swing.JTextArea jtaChatMessage;
    private javax.swing.JTextField jtfIPadress;
    // End of variables declaration//GEN-END:variables
}
